name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install platformio
        platformio upgrade --dev          
        platformio update
    - name: Run PlatformIO Tests
      run: platformio test --environment desktop
